version: '3'
services:
  app:
    restart: always
    build: .
    volumes:
      - ./image.jpeg:/app/image.jpeg
      - ./templates:/app/templates
    ports:
      - 80:80
    stdin_open: true
    tty: true